### PR TITLE
feat: read the TraceId from Header and propagate it

### PR DESCRIPTION
**Pull request by lfdesousa**
The goal of this PR is to add the capability to use interpret the W3C headers as specified here: https://www.w3.org/TR/trace-context/ and at the moment we dump them in the log, that according to the application.yml is sending them to the console.
Please note I might have added more than needed in the application.yml in particular regarding the health endpoints, if that is the case I will amend it.

### CODE REVIEW

**Comment by qligier** [comment]
Hi @lfdesousa! Thank you for this PR.
There was recently in IPF a move from Brave to Micrometer: https://github.com/oehf/ipf/commit/70d4cd739c5233ce8aa8683c8d111cdce5fa24ff
Does it impact this implementation? Should we do the same?

**Comment by oliveregger** [comment]
@lfdesousa will update the PR

**Comment by lfdesousa** [comment]
I did an update on this PR, I also updated something related with ITI67, in particular RouteBuilder, there was an exception when the Mag was starting, though I will need that to be reviewed.

**Comment by qligier** [comment]
Is it ready for review, or have you planned other changes?

In the route builder, the custom indentation helps to see the underlying structure of the route. It was particularly helpful here because of all the branching happening in this route.

**Comment by lfdesousa** [comment]
Let me just check the indentation and then it will be ready for review.

**Comment by lfdesousa** [comment]
I updated the identitation in the Route Builder, it should be better now, other than that I do not have other stuff to add for now.

**Comment by qligier** [comment]
I quickly implemented the manual forwarding of the header to other outgoing messages, to be tested during the Projectathon: https://github.com/i4mi/MobileAccessGateway/commit/0ce2029f38c4f33aa1040d5ad44853d718827573
There is one feature missing in IPF, we can't set HTTP headers in FHIR responses yet: https://github.com/oehf/ipf/issues/458. Otherwise, it should be working.

**Comment by qligier** [comment]
Rebased and merged in #186

**Pull request closed without merging**
