### PR TITLE
fix: patient get contact phone numbers / email

### PR DESCRIPTION
**Pull request by staffoleo**

### CODE REVIEW

**Comment by qligier** [comment]
Hi @staffoleo! Thanks for the PR.
Would you have an example of an HPD resource that would have 0, 2 or more colons in its telecom?

**Review by qligier — APPROVED** [review]

**Comment by qligier** [comment]
We are expecting the telecom as a URI because that's what HL7v3 requires: see URL and TEL in https://www.hl7.org/documentcenter/public/wg/inm/datatypes-its-xml20050714.htm#dtimpl-URL

Your real case scenario is invalid, but we could make an extra effort to detect common formats of email addresses and phone numbers.

**Comment by oliveregger** [comment]
discussion: detect email (@ symbol) otherwise don't set the system type

**Review by oliveregger — APPROVED** [review]

**Comment by oliveregger** [comment]
@staffoleo could you update the changelog too? https://github.com/i4mi/MobileAccessGateway/blob/master/docs/changelog.md

**Pull request merged**
