### PR TITLE
Feature/ipf dependency update

### PR DESCRIPTION
**Pull request by staffoleo**
Importing of https://github.com/unixoid/pton-ppqm by @unixoid.

Removing of ihe-europe dependency for sts wsdl.

### CODE REVIEW

**Comment by unixoid** [comment]
@oliveregger @qligier @Alexander-Kreutz 
Gentelemen,
Sorry for bothering you, but have you already had a chance to take a look at our pull request?

**Comment by qligier** [comment]
Hi @unixoid, @staffoleo 
Thank you for implementing PPQm! Unfortunately I had no time yet to review and test it. Do you need the feature to be merged quickly?

**Comment by staffoleo** [comment]
Hi @qligier, we don't need this in production right now, but in the incoming months I'm planning to send quite some PR. I started unit-testing the Mag. In our Pocket we'll need some thin production ready in 3 or 4 months.
Let's figure out how the collaboration model could work.     @unixoid: what do you think?

**Comment by qligier** [comment]
Hi @staffoleo!
The MAG doesn't boot any more if the PPQm endpoints are not configured: `URISyntaxException: Expected authority at index 10: ch-ppq1://`.
Do we have example endpoints to put in the base configuration? Or better, could you make the PPQm route build depend on the presence of the configuration properties? (Spring's @ConditionalOnProperty should do the trick here)
Thanks!

**Comment by unixoid** [comment]
@qligier, I added conditions on all route builders except the XUA-related ones.

**Comment by qligier** [comment]
Thanks @unixoid!

Now I have other issues:

```
2024-02-06 18:55:11.563  WARN 8016 --- [           main] o.a.c.component.cxf.jaxws.CxfEndpoint    : Error creating Cxf Bus from SpringBootCamelContext: org.apache.camel.component.cxf.spring.jaxws.CxfSpringEndpointUtils This exception will be ignored.
java.lang.ClassNotFoundException: org.apache.camel.component.cxf.spring.jaxws.CxfSpringEndpointUtils
```

Not sure if it is important, since Camel ignores it.

```
2024-02-06 18:56:28.008 ERROR 8016 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Error starting CamelContext (camel-1) due to exception thrown: Failed to start route assertionFromIdpToken because of Setting SSL failed
org.apache.camel.FailedToStartRouteException: Failed to start route assertionFromIdpToken because of Setting SSL failed
Caused by: java.lang.RuntimeException: Setting SSL failed
Caused by: java.security.KeyStoreException: Uninitialized keystore
```

This exception blocks the app launch, and I don't understand what is the cause here. I think it is because a dependency change, that configuration is working with the master branch just fine.
Was there a significant change in Camel's SSLContextParameters?

**Comment by unixoid** [comment]
@qligier:

1. Seems to be a manifestation of https://issues.apache.org/jira/browse/CAMEL-19305.  But yes, Camel seems to ignore it.
2. Seems to be the same issue as discussed in https://groups.google.com/g/ipf-user/c/6cCSe5uV4V4 -- prefix "file:" is required when referencing files on the file system and not in the classpath.  

BTW, despite all that, unit tests contained in the PR work without any problems.  Unfortunately, there are no other unit tests in the project that would help us understand whether the introduced changes break anything...

**Comment by qligier** [comment]
I'll try later the `file:` prefix, seems to be the probable cause, thanks!

Indeed, only caught by the prod tests :)

**Review by qligier — APPROVED** [review]

**Pull request merged**
